### ISSUE TITLE
Bug - Unrecognized option: --settings ./.mvn/settings.xml

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/reliable-web-app-pattern-java#35]
Error when running `mvn` commands to build or deploy the web app:

![Image](https://user-images.githubusercontent.com/23503973/217916676-37821fe4-171d-4741-aaf0-3db09c840a0d.png)

*known workaround*
1. delete the line from the `./.mvn/maven.config` file
1. append that line to the end of the `mvn` command as a parameter `--settings ./.mvn/settings.xml`

**Comment by agoncal** [comment]
I just bumped into this issue. 

FYIO this happens if you have Maven > 3.9 installed. If you have Maven up to 3.8.8, this does not happen. There was a [breaking change](https://maven.apache.org/docs/3.9.0/release-notes.html#potentially-breaking-core-changes-if-migrating-from-3-8-x) in 3.9:

> Each line in .mvn/maven.config is now interpreted as a single argument. That is, if the file contains multiple arguments, these must now be placed on separate lines, see [MNG-7684](https://issues.apache.org/jira/browse/MNG-7684).

So it's just a matter of changing the content of the `.mvn/maven.config` file from

```
--settings ./.mvn/settings.xml
```

to (adding a newline)

```
--settings
./.mvn/settings.xml
```

And this works for both Maven 3.8.x and 3.9.x

**Comment by agoncal** [comment]
I just bumped into this issue. 

FYIO this happens if you have Maven > 3.9 installed. If you have Maven up to 3.8.8, this does not happen. There was a [breaking change](https://maven.apache.org/docs/3.9.0/release-notes.html#potentially-breaking-core-changes-if-migrating-from-3-8-x) in 3.9:

> Each line in .mvn/maven.config is now interpreted as a single argument. That is, if the file contains multiple arguments, these must now be placed on separate lines, see [MNG-7684](https://issues.apache.org/jira/browse/MNG-7684).

So it's just a matter of changing the content of the `.mvn/maven.config` file from

```
--settings ./.mvn/settings.xml
```

to (adding a newline)

```
--settings
./.mvn/settings.xml
```

And this works for both Maven 3.8.x and 3.9.x
